### ISSUE TITLE
lib/DateTime/TimeZone/Zone/Asia/Riyadh87.pm6: No such file or directory

### ISSUE THREAD

**Issue by Altai-man** [supernovus/perl6-timezone#18]
META6.json claims it provides such a file, but there is only `Riyadh.pm6` without a number.

**Comment by patrickbkr** [comment]
This has been fixed with [commit 96c2ee3d4](https://github.com/supernovus/perl6-timezone/commit/96c2ee3d481fa6c93c00da3bf7213134710b157e).
